"""new names to set up associations

Revision ID: 18c6d06cbfd6
Revises: cb63b2bc96c2
Create Date: 2023-08-22 17:45:29.099125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18c6d06cbfd6'
down_revision: Union[str, None] = 'cb63b2bc96c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uld', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caster_deck_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('uld', type_='foreignkey')
        batch_op.create_foreign_key("uld_caster", 'caster_deck', ['caster_deck_id'], ['id'])
        batch_op.drop_column('caster_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uld', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caster_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint("uld_caster", type_='foreignkey')
        batch_op.create_foreign_key('uld', 'caster_deck', ['caster_id'], ['id'])
        batch_op.drop_column('caster_deck_id')

    # ### end Alembic commands ###
