"""set up one to many

Revision ID: 9c9cc83c9212
Revises: 67fd514d44fc
Create Date: 2023-08-22 17:29:13.139660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c9cc83c9212'
down_revision: Union[str, None] = '67fd514d44fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uld', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caster_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("uld_caster", 'caster_deck', ['caster_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uld', schema=None) as batch_op:
        batch_op.drop_constraint('uld_caster', type_='foreignkey')
        batch_op.drop_column('caster_id')

    # ### end Alembic commands ###
