"""change version none due to naming

Revision ID: cb63b2bc96c2
Revises: 9c9cc83c9212
Create Date: 2023-08-22 17:37:49.314888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb63b2bc96c2'
down_revision: Union[str, None] = '9c9cc83c9212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
